change koa-logger to version 1.3.0
koa-logger 2.0.0 does not support koa version 1. https://github.com/koajs/logger/tree/2.0.0
I just tested current master version in Ubuntu 14.04 x64, it showed:
> assert.js:89
>   throw new assert.AssertionError({
>   ^
> AssertionError: app.use() requires a generator function
>     at Application.app.use (/home/tutu/koa-rest/node_modules/koa/lib/application.js:106:5)
>     at Object.<anonymous> (/home/tutu/koa-rest/app.js:12:5)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:968:3